### ISSUE TITLE
Fail to getfactory implement instance for interface:com.qq.e.comm.pi.POFactory

### ISSUE THREAD

**Issue by ghyzx** [gdtmobsdk/GDTMobSDK#28]
请问这个报错信息是什么个情况？
Exception while init UnifiedBannerView plugin
    com.qq.e.comm.managers.plugin.c: Fail to getfactory implement instance for interface:com.qq.e.comm.pi.POFactory
        at com.qq.e.comm.managers.plugin.PM.getFactory(Unknown Source:164)
        at com.qq.e.comm.managers.plugin.PM.getPOFactory(Unknown Source:2)
        at com.qq.e.ads.banner2.UnifiedBannerView$1.run(Unknown Source:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.NoClassDefFoundError: com.qq.e.comm.plugin.POFactoryImpl
        at java.lang.reflect.Method.invoke(Native Method)
        at com.qq.e.comm.managers.plugin.PM.getFactory(Unknown Source:93)
        at com.qq.e.comm.managers.plugin.PM.getPOFactory(Unknown Source:2) 
        at com.qq.e.ads.banner2.UnifiedBannerView$1.run(Unknown Source:22) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: java.lang.ExceptionInInitializerError
        at yaq.pro.getobjresult(Native Method)
        at com.qq.e.comm.plugin.w.a.a(Unknown Source:6)
        at com.qq.e.comm.plugin.POFactoryImpl.<init>(A:105)
        at com.qq.e.comm.plugin.POFactoryImpl.<clinit>(A:94)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.qq.e.comm.managers.plugin.PM.getFactory(Unknown Source:93)
        at com.qq.e.comm.managers.plugin.PM.getPOFactory(Unknown Source:2)
        at com.qq.e.comm.services.a$1.onResponse(Unknown Source:127)
        at com.qq.e.comm.net.NetworkClientImpl$TaskCallable.call(Unknown Source:98)
        at com.qq.e.comm.net.NetworkClientImpl$TaskCallable.call(Unknown Source:0)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: java.lang.RuntimeException: load lib error
        at yaq.pro.<clinit>(pro.java:179)
        at yaq.pro.getobjresult(Native Method) 
        at com.qq.e.comm.plugin.w.a.a(Unknown Source:6) 
        at com.qq.e.comm.plugin.POFactoryImpl.<init>(A:105) 
        at com.qq.e.comm.plugin.POFactoryImpl.<clinit>(A:94) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.qq.e.comm.managers.plugin.PM.getFactory(Unknown Source:93) 
        at com.qq.e.comm.managers.plugin.PM.getPOFactory(Unknown Source:2) 
        at com.qq.e.comm.services.a$1.onResponse(Unknown Source:127) 
        at com.qq.e.comm.net.NetworkClientImpl$TaskCallable.call(Unknown Source:98) 
        at com.qq.e.comm.net.NetworkClientImpl$TaskCallable.call(Unknown Source:0) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by CoCoXXXX** [comment]
解决了吗，请问

**Comment by yudeshuai** [comment]
我也遇到了。怎么解决呢

**Comment by hulasika-fo** [comment]
继续挖坟。

**Comment by xinxiangshichengddd** [comment]
解决了吗
